N_missions = 100        # Number of missions per test series
N_vehicles = 2          # Number of vehicles per mission
N_RS = 4                # Number of RuleSets
N_TS = 4                # Number of test series
t_extra = 5.            # Time on top of the lookaheadtime
ref_position = "EHVB"   # Reference position
ref_alt = 1000.         # Reference altitude [ft]
min_vel_RC = 5.         # minimum initial speed for Rotorcraft
R_PZ = 50.              # Radius od protected zone [m]